Attribute VB_Name = "questions"
Public Question(51) As String
Public Answer1(51) As String
Public Answer2(51) As String
Public Answer3(51) As String
Public Answer4(51) As String
Public Correct(51) As Byte
Public Quedone(15) As Byte
Public Questno As Byte
Public Guess As Byte
Public Fiftyfifty As Boolean
Public Pollaud As Boolean
Public Phone As Boolean
Public Phoney As Byte
Public Questans As Boolean
Public Wrong As Boolean
Public Quedonecount As Byte
Public Fiftychange As Boolean
Public Random50 As Byte
Public Random250 As Byte
Public Random350 As Byte
Public AnsA As Byte
Public AnsB As Byte
Public AnsC As Byte
Public AnsD As Byte
Public Random As Integer
'These are the variables for Lifelines and questions
